### ISSUE TITLE
Finish Zipper module

### ISSUE THREAD

**Issue by orbit1690** [orbit1690/global-rankings#2]

**Comment by orbit1690** [comment]
@HadarNahshon @yehonatancohen

**Comment by giladwo** [comment]
https://github.com/orbit1690/global-rankings/pull/4#pullrequestreview-336764199
These fixes are needed, so I'm not closing this issue.

**Comment by giladwo** [comment]
Since we don't have much time until the kick off, we're going to use an external zipper - [wernerdegroot/listzipper](https://package.elm-lang.org/packages/wernerdegroot/listzipper/latest/List-Zipper).
@HadarNahshon don't be sorry your implementation isn't used. You've learned from it and you're going to spend your time on more important parts :slightly_smiling_face:

**Comment by giladwo** [comment]
Since we don't have much time until the kick off, we're going to use an external zipper - [wernerdegroot/listzipper](https://package.elm-lang.org/packages/wernerdegroot/listzipper/latest/List-Zipper).
@HadarNahshon don't be sorry your implementation isn't used. You've learned from it and you're going to spend your time on more important parts :slightly_smiling_face:
